do 26 mrt  11:04

Nieuwe cijfers voor ons land: 1.298 nieuwe besmettingen, 536 nieuwe opnames in het ziekenhuis en 42 nieuwe overlijdens
Het Nationaal Crisiscentrum heeft zijn dagelijkse cijferupdate gegeven. 

Er zijn 1.298 nieuwe bevestigde besmettingen. 
Het totaal aantal bevestigde patiënten nu op 6.235.
Er zijn 536 nieuwe ziekenhuisopnames. 
In totaal liggen er nu 2.652 mensen in het ziekenhuis, 605 van hen liggen op intensieve zorg.
Er zijn 42 nieuwe overlijdens gemeld.
In totaal stierven al 220 patiënten aan de gevolgen van het coronavirus.
